
# This config file is meant for settings that affect your whole project,
# values which you are expected to set up once and rarely need to edit after
# that. For technical reasons, this file is *NOT* reloaded automatically when
# you use 'jekyll serve'. If you change this file, please restart the server
# process.

# this shows up in the tab, and is the default name if the page is saved
title: Peter Henry Resume

# show up in the preview text when linking the site in some contexts
description: Resume builder using Jekyll static site generation.

 # the subpath of your site, e.g. /blog
baseurl: ""

# the base hostname & protocol for your site
url: "http://peterhenry.net"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  sass_dir: _sass

color: white;